In [2]:
import pandas as pd
df = pd.read_csv(r'c:\Users\ASUS\Downloads\archive (6)\employee_attrition_dataset.csv')

In [3]:
df.head(3)

,Employee_ID,Age,Gender,Marital_Status,Department,Job_Role,Job_Level,Monthly_Income,Hourly_Rate,Years_at_Company,...,Overtime,Project_Count,Average_Hours_Worked_Per_Week,Absenteeism,Work_Environment_Satisfaction,Relationship_with_Manager,Job_Involvement,Distance_From_Home,Number_of_Companies_Worked,Attrition
0,1,58,Female,Married,IT,Manager,1,15488,28,15,...,No,6,54,17,4,4,4,20,3,No
1,2,48,Female,Married,Sales,Assistant,5,13079,28,6,...,Yes,2,45,1,4,1,2,25,2,No
2,3,34,Male,Married,Marketing,Assistant,1,13744,24,24,...,Yes,6,34,2,3,4,4,45,3,No

In [4]:
df['Gender'].unique()

<StringArray>
['Female', 'Male']
Length: 2, dtype: str

In [5]:
df['Marital_Status'].unique()

<StringArray>
['Married', 'Divorced', 'Single']
Length: 3, dtype: str

In [6]:
df['Job_Level'].unique()

array([1, 5, 3, 2, 4])

In [7]:
df[['Department', 'Job_Role', 'Overtime', 'Attrition']].apply(lambda x: x.unique())

Department         [IT, Sales, Marketing, Finance, HR]
Job_Role      [Manager, Assistant, Executive, Analyst]
Overtime                                     [No, Yes]
Attrition                                    [No, Yes]
dtype: object

In [8]:
df.isnull().sum()

Employee_ID                      0
Age                              0
Gender                           0
Marital_Status                   0
Department                       0
Job_Role                         0
Job_Level                        0
Monthly_Income                   0
Hourly_Rate                      0
Years_at_Company                 0
Years_in_Current_Role            0
Years_Since_Last_Promotion       0
Work_Life_Balance                0
Job_Satisfaction                 0
Performance_Rating               0
Training_Hours_Last_Year         0
Overtime                         0
Project_Count                    0
Average_Hours_Worked_Per_Week    0
Absenteeism                      0
Work_Environment_Satisfaction    0
Relationship_with_Manager        0
Job_Involvement                  0
Distance_From_Home               0
Number_of_Companies_Worked       0
Attrition                        0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.dtypes

Employee_ID                      int64
Age                              int64
Gender                             str
Marital_Status                     str
Department                         str
Job_Role                           str
Job_Level                        int64
Monthly_Income                   int64
Hourly_Rate                      int64
Years_at_Company                 int64
Years_in_Current_Role            int64
Years_Since_Last_Promotion       int64
Work_Life_Balance                int64
Job_Satisfaction                 int64
Performance_Rating               int64
Training_Hours_Last_Year         int64
Overtime                           str
Project_Count                    int64
Average_Hours_Worked_Per_Week    int64
Absenteeism                      int64
Work_Environment_Satisfaction    int64
Relationship_with_Manager        int64
Job_Involvement                  int64
Distance_From_Home               int64
Number_of_Companies_Worked       int64
Attrition                          str
dtype: object

In [11]:
df.rename(columns= {'Absenteeism' : 'Absent_days'}, inplace=True)

In [12]:
df.tail(5)

,Employee_ID,Age,Gender,Marital_Status,Department,Job_Role,Job_Level,Monthly_Income,Hourly_Rate,Years_at_Company,...,Overtime,Project_Count,Average_Hours_Worked_Per_Week,Absent_days,Work_Environment_Satisfaction,Relationship_with_Manager,Job_Involvement,Distance_From_Home,Number_of_Companies_Worked,Attrition
995,996,27,Female,Divorced,HR,Analyst,2,4172,76,24,...,No,4,46,10,3,1,4,24,4,No
996,997,47,Male,Single,IT,Manager,4,11007,71,19,...,Yes,7,36,16,3,2,4,39,3,Yes
997,998,50,Female,Divorced,IT,Executive,1,4641,43,25,...,Yes,1,46,9,2,3,3,33,2,No
998,999,28,Female,Married,HR,Executive,4,19855,92,13,...,No,4,52,17,4,1,4,41,4,No
999,1000,48,Female,Divorced,IT,Analyst,2,11738,39,1,...,Yes,2,59,5,1,4,3,43,2,No

In [13]:
df.to_csv('Hr_Cleaned_Dataset.csv',index=False)